### ISSUE TITLE
invalid JSON is being produced once formatted

### ISSUE THREAD

**Issue by ccoVeille** [hougesen/mdsf#147]
Here is a content that is wrongly formatted

````markdown
This is the content of a markdown file

```json
{
        "foo": "bar",
        "user_id": "2313",
        "scope": ["internal"]
}
```
````

````markdown
This is the content of a markdown file

```json
{
  "foo": "bar",
  "user_id": "2313",
  "scope": ["internal"],
}
```
````

The extra comma at the end of the list lead to an invalid json

Here is my mdsf.json

```
{
  "$schema": "https://raw.githubusercontent.com/hougesen/mdsf/main/schemas/v0.0.2/mdsf.schema.json",
  "json": {
    "enabled": true,
    "formatter": [
      [
        "prettier"
      ]
    ]
  }
}
```

prettier 3.2.5 is installed and work well.

**Comment by ccoVeille** [comment]
The point I raised in #146 is interesting here as I have no way to know what formatter is being applied.

**Comment by ccoVeille** [comment]
It seems to me you are using jsonc format which supports comments and extra trailing comma

These two formats should be handled separately.

````markdown
```json
{
        "foo": "bar",
        "user_id": "2313",
        "scope": ["internal"]
}
```
````

````markdown
```jsonc
{
        "foo": "bar",
        "user_id": "2313",
        "scope": ["internal"] // some comment
}
```
````

**Comment by ccoVeille** [comment]
it might be related to this https://github.com/prettier/prettier/issues/15956

**Comment by hougesen** [comment]
The reason json is formatted as jsonc is because people often have comments in their json codeblocks, which isn't part of the specification. 

But I just did a quick test and it seems that both prettier and deno supports formatting json files with comments. Sadly Biome does not expose the argument for allowing comments (https://github.com/biomejs/biome/blob/a6f5f0e8187912b389bf88ece65a51f1e02027a6/crates/biome_service/src/configuration/json.rs#L31).

I was already planning on introducing language “flavors” (`css -> css, scss, sass, less`, `json -> json, jsonc, json5`, `sh -> sh, zsh, bash`), which should fix the issue.
